'''
¿Cuál es la salida del siguiente código?

R//Error no puede faltar ningun argumento

'''
def add_numbers(a, b=2, c):
    print(a + b + c)

add_numbers(a=1, c=3)